#!/usr/bin/env bun
import { readdir } from "node:fs/promises";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const placesDir = join(root, "places");
const itemsFile = join(root, "items.json");
const indexMdFile = join(root, "INDEX.md");

interface Place {
  placeId: string;
  displayName: string;
  mrn: string;
  timezone: string;
  tags: string[];
  coordinate: { lat: number; lng: number };
  provider: { platform: string; name: string; resources: unknown[] };
}

function fail(where: string, msg: string): never {
  throw new Error(`${where}: ${msg}`);
}

function check(cond: unknown, where: string, msg: string): asserts cond {
  if (!cond) fail(where, msg);
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function validateResource(res: unknown, where: string) {
  check(isObject(res), where, "expected an object");
  check(typeof res.id === "string", where, "missing string `id`");
  check(typeof res.name === "string", where, "missing string `name`");
  check(typeof res.mrn === "string", where, "missing string `mrn`");
  check(Array.isArray(res.slots), where, "missing array `slots`");
  check(Array.isArray(res.tags), where, "missing array `tags`");
}

function validatePlace(place: unknown, where: string) {
  check(isObject(place), where, "expected an object");
  check(typeof place.placeId === "string", where, "missing string `placeId`");
  check(typeof place.displayName === "string", where, "missing string `displayName`");
  check(typeof place.mrn === "string", where, "missing string `mrn`");
  check(typeof place.timezone === "string", where, "missing string `timezone`");
  check(Array.isArray(place.tags), where, "missing array `tags`");

  check(isObject(place.coordinate), `${where}.coordinate`, "expected an object");
  check(typeof place.coordinate.lat === "number", `${where}.coordinate`, "missing number `lat`");
  check(typeof place.coordinate.lng === "number", `${where}.coordinate`, "missing number `lng`");

  const provider = place.provider;
  check(isObject(provider), `${where}.provider`, "expected an object");
  check(typeof provider.platform === "string", `${where}.provider`, "missing string `platform`");
  check(typeof provider.name === "string", `${where}.provider`, "missing string `name`");
  check(Array.isArray(provider.resources), `${where}.provider`, "missing array `resources`");
  provider.resources.forEach((res, i) =>
    validateResource(res, `${where}.provider.resources[${i}]`),
  );
}

function renderPlacesMd(groups: { provider: string; places: Place[] }[]): string {
  const total = groups.reduce((n, g) => n + g.places.length, 0);
  const courts = groups.reduce(
    (n, g) => n + g.places.reduce((m, p) => m + p.provider.resources.length, 0),
    0,
  );
  const lines: string[] = [
    "# Index",
    "",
    "_Generated by `bun run build` — do not edit by hand._",
    "",
    `${total} places across ${groups.length} providers, ${courts} courts total.`,
    "",
  ];
  for (const { provider, places } of groups) {
    lines.push(`## ${provider}`, "");
    lines.push("| Place | Courts | Tags | Coordinate | Timezone |");
    lines.push("|-------|--------|------|------------|----------|");
    for (const p of places) {
      const coord = `${p.coordinate.lat}, ${p.coordinate.lng}`;
      const tags = p.tags.length ? p.tags.join(", ") : "—";
      lines.push(
        `| ${p.displayName} | ${p.provider.resources.length} | ${tags} | ${coord} | ${p.timezone} |`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

const files = (await readdir(placesDir)).filter((f) => f.endsWith(".json")).sort();
console.log(`composing ${files.length} place files`);

const items: Place[] = [];
const groups: { provider: string; places: Place[] }[] = [];
const seenPlaceIds = new Set<string>();
for (const file of files) {
  const data = await Bun.file(join(placesDir, file)).json();
  check(typeof data.provider === "string", file, "missing string `provider`");
  check(Array.isArray(data.places), file, `expected a "places" array, got ${typeof data.places}`);

  data.places.forEach((place: unknown, i: number) => {
    const where = `${file} places[${i}]`;
    validatePlace(place, where);
    const placeId = (place as Record<string, unknown>).placeId as string;
    check(!seenPlaceIds.has(placeId), where, `duplicate placeId \`${placeId}\``);
    seenPlaceIds.add(placeId);
  });

  console.log(`  ${file}: ${data.places.length} places (provider ${data.provider})`);
  items.push(...(data.places as Place[]));
  groups.push({ provider: data.provider, places: data.places as Place[] });
}

await Bun.write(itemsFile, JSON.stringify(items, null, 2) + "\n");
console.log(`wrote ${items.length} items to items.json`);

await Bun.write(indexMdFile, renderPlacesMd(groups));
console.log(`wrote INDEX.md`);
