#!/usr/bin/env bun
import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { PROVIDERS } from "../src/providers";

const root = new URL("..", import.meta.url).pathname;
const providersDir = join(root, "providers");
const itemsFile = join(root, "items.json");
const indexMdFile = join(root, "INDEX.md");

interface Place {
  placeId: string;
  displayName: string;
  mrn: string;
  timezone: string;
  tags: string[];
  coordinate: { lat: number; lng: number };
  provider: { platform: string; name: string; resources: unknown[] };
}

function fail(where: string, msg: string): never {
  throw new Error(`${where}: ${msg}`);
}

function check(cond: unknown, where: string, msg: string): asserts cond {
  if (!cond) fail(where, msg);
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function validateResource(res: unknown, where: string) {
  check(isObject(res), where, "expected an object");
  check(typeof res.name === "string", where, "missing string `name`");
  check(typeof res.mrn === "string", where, "missing string `mrn`");
  check(Array.isArray(res.slots), where, "missing array `slots`");
  check(Array.isArray(res.tags), where, "missing array `tags`");
}

function validatePlace(place: unknown, where: string) {
  check(isObject(place), where, "expected an object");
  check(typeof place.placeId === "string", where, "missing string `placeId`");
  check(typeof place.displayName === "string", where, "missing string `displayName`");
  check(typeof place.mrn === "string", where, "missing string `mrn`");
  check(typeof place.timezone === "string", where, "missing string `timezone`");
  check(Array.isArray(place.tags), where, "missing array `tags`");

  check(isObject(place.coordinate), `${where}.coordinate`, "expected an object");
  check(typeof place.coordinate.lat === "number", `${where}.coordinate`, "missing number `lat`");
  check(typeof place.coordinate.lng === "number", `${where}.coordinate`, "missing number `lng`");

  const provider = place.provider;
  check(isObject(provider), `${where}.provider`, "expected an object");
  check(typeof provider.platform === "string", `${where}.provider`, "missing string `platform`");
  check(typeof provider.name === "string", `${where}.provider`, "missing string `name`");
  check(Array.isArray(provider.resources), `${where}.provider`, "missing array `resources`");
  provider.resources.forEach((res, i) =>
    validateResource(res, `${where}.provider.resources[${i}]`),
  );
}

function providerOf(place: Place): string {
  return place.mrn.split(":").slice(0, 2).join(":");
}

function renderPlacesMd(groups: Map<string, Place[]>): string {
  const all = [...groups.values()].flat();
  const total = all.length;
  const courts = all.reduce((n, p) => n + p.provider.resources.length, 0);
  const lines: string[] = [
    "# Index",
    "",
    "_Generated by `bun run build` - do not edit by hand._",
    "",
    `${total} places across ${groups.size} providers, ${courts} courts total.`,
    "",
  ];
  for (const [provider, places] of groups) {
    lines.push(`## ${provider}`, "");
    lines.push("| Place | Courts | Tags | Coordinate | Timezone |");
    lines.push("|-------|--------|------|------------|----------|");
    for (const p of places) {
      const coord = `${p.coordinate.lat}, ${p.coordinate.lng}`;
      const tags = p.tags.length ? p.tags.join(", ") : "-";
      lines.push(
        `| ${p.displayName} | ${p.provider.resources.length} | ${tags} | ${coord} | ${p.timezone} |`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

const providerDirs = (
  await readdir(providersDir, { withFileTypes: true })
)
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();
console.log(`composing ${providerDirs.length} providers`);

const items: Place[] = [];
const groups = new Map<string, Place[]>();
const seenPlaceIds = new Set<string>();
for (const dir of providerDirs) {
  const file = join("providers", dir, "places.json");
  const places = await Bun.file(join(providersDir, dir, "places.json")).json();
  check(Array.isArray(places), file, `expected an array of places, got ${typeof places}`);

  places.forEach((place: unknown, i: number) => {
    const where = `${file} places[${i}]`;
    validatePlace(place, where);
    const p = place as Place;
    check(!seenPlaceIds.has(p.placeId), where, `duplicate placeId \`${p.placeId}\``);
    seenPlaceIds.add(p.placeId);
    const provider = providerOf(p);
    const providerConfig = PROVIDERS[provider];
    check(providerConfig, where, `missing configured provider \`${provider}\``);
    check(p.provider.platform === providerConfig.platform, where, `provider platform does not match \`${provider}\``);
    if (!groups.has(provider)) groups.set(provider, []);
    groups.get(provider)!.push(p);
  });

  console.log(`  ${dir}: ${places.length} places`);
  items.push(...(places as Place[]));
}

await Bun.write(itemsFile, JSON.stringify(items, null, 2) + "\n");
console.log(`wrote ${items.length} items to items.json`);

await Bun.write(indexMdFile, renderPlacesMd(groups));
console.log(`wrote INDEX.md`);
